### ISSUE TITLE
onHostDestroy

### ISSUE THREAD

**Issue by 277850318** [narayananvenk/react-native-paypal#2]
@Override
    public void onHostDestroy() {
        //activity.stopService(new Intent(activity, PayPalService.class));
                //this is ok can run

```
            activity.stopService(new Intent(activity, PayPalService.class));
             //this will have a error
}  
```

ava.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=-1, data=Intent { (has extras) }} to activity {com.quecent/com.quecent.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3706)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3749)
    at android.app.ActivityThread.access$1400(ActivityThread.java:153)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5438)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
    at android.content.ComponentName.<init>(ComponentName.java:128)
    at android.content.Intent.<init>(Intent.java:4453)
---------------->   at com.rnpaypal.PaypalModule.onActivityResult(PaypalModule.java:164)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:202)
    at com.facebook.react.ReactInstanceManagerImpl.onActivityResult(ReactInstanceManagerImpl.java:612)
    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:184)
    at com.quecent.MainActivity.onActivityResult(MainActivity.java:36)
    at android.app.Activity.dispatchActivityResult(Activity.java:6508)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3702)
    ... 9 more

**Comment by 277850318** [comment]
"react-native": "0.28.0",   android

**Comment by narayananvenk** [comment]
Can you provide some info on how to replicate this?

**Comment by 277850318** [comment]
on app start and do nothing and  exit,it will happen.    i  have no pay,but react-native-paypal will be execute,why?

**Comment by narayananvenk** [comment]
I am unable to replicate this issue. Are you overriding the onAcitivtyResult in your MainActivity.java or modifying this module? can you post that code here?

**Comment by narayananvenk** [comment]
Found it. Can you check if 8f77ffb fixes it?
